package com.sanket_satpute_20.ironmind.domain.model.observation

enum class ObservationType {
    APP_OPENED,
    APP_CLOSED,
    NOTIFICATION_RECEIVED,
    NOTIFICATION_INTERACTED,
    TASK_STARTED,
    TASK_COMPLETED,
    TASK_POSTPONED,
    COMMITMENT_STARTED,
    COMMITMENT_COMPLETED,
    COMMITMENT_POSTPONED,
    COMMITMENT_MISSED,
    LOCATION_CONTEXT_CHANGED,
    CALENDAR_CONTEXT_CHANGED,
    VOICE_CAPTURED,
    USER_INPUT,
    UNKNOWN
}
