package com.sanket_satpute_20.ironmind.domain.model

enum class EventType {
    GOAL_CREATED,
    GOAL_UPDATED,
    GOAL_COMPLETED,
    GOAL_PAUSED,
    GOAL_ABANDONED,
    GOAL_REACTIVATED,
    
    AMBITION_CREATED,
    AMBITION_UPDATED,
    AMBITION_COMPLETED,
    AMBITION_PAUSED,
    AMBITION_ABANDONED,
    
    PLAN_CREATED,
    PLAN_UPDATED,
    PLAN_ACTIVATED,
    PLAN_COMPLETED,
    PLAN_PAUSED,
    PLAN_REPLACED,
    
    TASK_CREATED,
    TASK_STARTED,
    TASK_COMPLETED,
    TASK_POSTPONED,
    TASK_CANCELLED,
    TASK_ABANDONED,
    
    COMMITMENT_CREATED,
    COMMITMENT_COMMITTED,
    COMMITMENT_STARTED,
    COMMITMENT_COMPLETED,
    COMMITMENT_POSTPONED,
    COMMITMENT_RESCHEDULED,
    COMMITMENT_MISSED,
    COMMITMENT_RECOVERED,
    COMMITMENT_ABANDONED,
    
    OUTCOME_RECORDED,
    
    REFLECTION_CREATED,
    REFLECTION_STARTED,
    REFLECTION_COMPLETED,
    REFLECTION_FAILED,
    
    VOICE_CAPTURED,
    VOICE_TRANSCRIBED,
    VOICE_TRANSCRIPTION_FAILED,
    
    PROTECTION_STARTED,
    PROTECTION_ENDED,
    PROTECTION_ENABLED,
    PROTECTION_DISABLED,
    PROTECTION_OVERRIDDEN,
    PROTECTION_EXPIRED,
    
    INTERVENTION_PROPOSED,
    INTERVENTION_TRIGGERED,
    INTERVENTION_DELIVERED,
    INTERVENTION_ACCEPTED,
    INTERVENTION_DISMISSED,
    INTERVENTION_IGNORED,
    INTERVENTION_OVERRIDDEN,
    INTERVENTION_EXPIRED,
    
    MEMORY_CREATED,
    MEMORY_UPDATED,
    MEMORY_REJECTED,
    MEMORY_EXPIRED,
    
    PATTERN_CREATED,
    PATTERN_UPDATED,
    PATTERN_CONFIRMED,
    PATTERN_REJECTED,
    PATTERN_DECAYED,
    PATTERN_DEACTIVATED,
    
    SYNC_STARTED,
    SYNC_COMPLETED,
    SYNC_FAILED,
    SYNC_RETRIED,
    
    BACKGROUND_JOB_STARTED,
    BACKGROUND_JOB_COMPLETED,
    BACKGROUND_JOB_FAILED
}
