package com.sanket_satpute_20.ironmind.data.ai

import com.sanket_satpute_20.ironmind.domain.ai.AIOutput
import com.sanket_satpute_20.ironmind.domain.ai.AIRequestType
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.IOException

class GeminiIronMindAITest {

    @Test
    fun `parseAndValidateOutput parses valid INTENT json correctly`() {
        val json = """
            {
                "type": "INTENT",
                "confidence": 0.85,
                "reasoning": "User explicitly stated their goal.",
                "schemaVersion": 1,
                "intentDescription": "Go to the gym tomorrow"
            }
        """.trimIndent()
        
        val output = GeminiIronMindAI.parseAndValidateOutput(json, AIRequestType.INTENT_EXTRACTION)
        assertTrue(output is AIOutput.IntentOutput)
        val intentOutput = output as AIOutput.IntentOutput
        assertEquals("Go to the gym tomorrow", intentOutput.intentDescription)
        assertEquals(0.85f, intentOutput.confidence)
        assertEquals("User explicitly stated their goal.", intentOutput.reasoning)
        assertEquals(1, intentOutput.schemaVersion)
    }

    @Test
    fun `parseAndValidateOutput parses valid SUMMARY json correctly`() {
        val json = """
            ```json
            {
                "type": "SUMMARY",
                "confidence": 0.9,
                "reasoning": "Standard summary",
                "schemaVersion": 1,
                "summaryText": "This is a summary."
            }
            ```
        """.trimIndent()
        
        val output = GeminiIronMindAI.parseAndValidateOutput(json, AIRequestType.SUMMARIZE)
        assertTrue(output is AIOutput.Summary)
        val summaryOutput = output as AIOutput.Summary
        assertEquals("This is a summary.", summaryOutput.summaryText)
        assertEquals(0.9f, summaryOutput.confidence)
    }

    @Test
    fun `parseAndValidateOutput parses valid INTERVENTION_RECOMMENDATION json correctly`() {
        val json = """
            {
                "type": "INTERVENTION_RECOMMENDATION",
                "confidence": 0.8,
                "schemaVersion": 2,
                "interventionType": "PROTECT",
                "recommendation": "Block distraction",
                "reason": "User is distracted",
                "targetEntityId": "goal-1",
                "targetEntityType": "GOAL"
            }
        """.trimIndent()
        
        val output = GeminiIronMindAI.parseAndValidateOutput(json, AIRequestType.INTERVENTION_SUGGESTION)
        assertTrue(output is AIOutput.InterventionRecommendation)
        val intervention = output as AIOutput.InterventionRecommendation
        assertEquals(com.sanket_satpute_20.ironmind.domain.ai.InterventionType.PROTECT, intervention.interventionType)
        assertEquals("Block distraction", intervention.recommendation)
        assertEquals("goal-1", intervention.targetEntityId)
        assertEquals("GOAL", intervention.targetEntityType)
        assertEquals(0.8f, intervention.confidence)
        assertEquals(2, intervention.schemaVersion)
    }

    @Test
    fun `parseAndValidateOutput returns NoAction for unknown type`() {
        val json = """
            {
                "type": "MADE_UP_TYPE",
                "confidence": 0.5,
                "schemaVersion": 1
            }
        """.trimIndent()
        
        val output = GeminiIronMindAI.parseAndValidateOutput(json, AIRequestType.INTENT_EXTRACTION)
        assertTrue(output is AIOutput.NoAction)
        val noAction = output as AIOutput.NoAction
        assertTrue(noAction.reason?.contains("Unrecognized output type") == true)
    }

    @Test
    fun `parseAndValidateOutput returns NoAction for invalid bounds`() {
        val json = """
            {
                "type": "INTENT",
                "confidence": 1.5,
                "intentDescription": "Go to the gym",
                "schemaVersion": 1
            }
        """.trimIndent()
        
        // Confidence > 1.0 is invalid per contract
        val output = GeminiIronMindAI.parseAndValidateOutput(json, AIRequestType.INTENT_EXTRACTION)
        assertTrue(output is AIOutput.NoAction)
        assertEquals("Invalid AI output generated by model.", (output as AIOutput.NoAction).reason)
    }

    @Test(expected = IOException::class)
    fun `parseAndValidateOutput throws IOException for malformed JSON`() {
        val json = "This is not json"
        GeminiIronMindAI.parseAndValidateOutput(json, AIRequestType.INTENT_EXTRACTION)
    }
}
