package com.sanket_satpute_20.ironmind.domain.ai

enum class AIOutputType {
    INTENT,
    PLAN,
    TASK,
    COMMITMENT,
    REFLECTION_EXTRACTION,
    PATTERN_CANDIDATE,
    MEMORY_CANDIDATE,
    INTERVENTION_RECOMMENDATION,
    BARRIER,
    SUMMARY,
    CLARIFICATION_REQUEST,
    NO_ACTION,
    CONTEXT_SYNTHESIS
}
