package com.sanket_satpute_20.ironmind.domain.ai

enum class AIRequestType {
    INTENT_EXTRACTION,
    REFLECTION_UNDERSTANDING,
    INTERVENTION_SUGGESTION,
    SUMMARIZE,
    PATTERN_PROPOSAL,
    PLAN_GENERATION,
    BARRIER_UNDERSTANDING,
    CONTEXT_SYNTHESIS,
    INTERVENTION_LEARNING,
    TIMING_LEARNING,
    CHANNEL_SELECTION,
    EXPERIMENT_PROPOSAL,
    MODEL_EVOLUTION
}
